### ISSUE TITLE
Documentation: Parameter ssl_extra_chain_certs appears twice with different descriptions

### ISSUE THREAD

**Issue by fchouina** [logstash-plugins/logstash-input-tcp#126]
Parameter "ssl_extra_chain_certs" appears twice with different descriptions.
This documentation error appears in versions 6.4 and 6.5 of the Logstash Reference Guide.

The first of the 2 occurences of the "ssl_extra_chain_certs" parameter is linked as:
https://www.elastic.co/guide/en/logstash/6.5/plugins-inputs-tcp.html#plugins-inputs-tcp-**ssl_certificate_authorities**

I assume that the name is wrong and this parameter should be named ssl_certificate_authorities as in the link.

**Comment by jsvd** [comment]
well spotted, fixed in #130, doc fixes will show up soon in elastic.co

**Comment by kreiger** [comment]
Hey, what's the status of this?

Docs are still wrong, and it cost us a couple of days.
