### ISSUE TITLE
Received fatal alert: unknown_ca

### ISSUE THREAD

**Issue by bobrik** [logstash-plugins/logstash-input-tcp#24]
```
SSL Error {:exception=>#<OpenSSL::SSL::SSLError: Received fatal alert: unknown_ca>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:262:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.12-java/lib/jopenssl19/openssl/ssl-internal.rb:106:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:108:in `run_server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:80:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:180:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:174:in `start_input'"], :level=>:error, :file=>"logstash/inputs/tcp.rb", :line=>"113", :method=>"run_server"}
```

Happens on 2.0.0 with the following config:

```
input {
  tcp {
    host       => "0.0.0.0"
    port       => 12345
    ssl_enable => true
    ssl_cert   => "/etc/logstash/ssl/cert"
    ssl_key    => "/etc/logstash/ssl/key"
  }
}
```

**Comment by bobrik** [comment]
```
IOError: closed stream
                  peeraddr at org/jruby/ext/socket/RubyIPSocket.java:95
                  peeraddr at org/jruby/ext/openssl/SSL.java:209
                      peer at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/util/socket_peer.rb:5
             handle_socket at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:162
  server_connection_thread at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:140
```

**Comment by bobrik** [comment]
```diff
diff --git a/dockerfiles/logstash/kafka-from-syslog-tls/tcp.rb b/dockerfiles/logstash/kafka-from-syslog-tls/tcp.rb
index 9e2272c..ba5d3dc 100644
--- a/dockerfiles/logstash/kafka-from-syslog-tls/tcp.rb
+++ b/dockerfiles/logstash/kafka-from-syslog-tls/tcp.rb
@@ -135,9 +135,12 @@ class LogStash::Inputs::Tcp < LogStash::Inputs::Base

   def server_connection_thread(output_queue, socket)
     Thread.new(output_queue, socket) do |q, s|
+      p = s.peer
       begin
         @logger.debug? && @logger.debug("Accepted connection", :client => s.peer, :server => "#{@host}:#{@port}")
         handle_socket(s, s.peeraddr[3], q, @codec.clone)
+      rescue
+        @logger.error("WTF", :client => p)
       ensure
         delete_connection_socket(s)
       end
```

**Comment by purbon** [comment]
@bobrik was trying to reproduce your issue by adding some SSL test for this plugin, i'm not able to reproduce for now. I wonder which versions are you using, If I understand you issue properly, the peer call is failing, right?

**Comment by bobrik** [comment]
Yes, peer is failing. Looking at my report I see `logstash-input-tcp-2.0.4`.

**Comment by purbon** [comment]
@bobrik I run your exact config, but everything works nice. I wonder if you had any DNS issue with your address resolution? can you check that? what do you think?

**Comment by bobrik** [comment]
I have no idea what was wrong 26 days ago. I have stack traces though.

We switched to syslog-ng and lived happily ever after.

**Comment by purbon** [comment]
Oh, I understand.

**Comment by dbason** [comment]
I am also seeing the same issue on CentOS6.  We have a cert signed by an internal CA, the CA is added to the trusted store using update-ca-trust.

The same certificate works fine using a beats input, but on the tcp input it fails with the error @bobrik reported.  Unfortunately switching isn't an option for us (at least until the windows eventlog beat is finished).

**Comment by jordansissel** [comment]
https://github.com/logstash-plugins/logstash-input-tcp/pull/43 should solve this crash.

**Comment by jordansissel** [comment]
#43 has been merged and released as plugin version 3.0.2. I'm going to close this issue since I think it's resolved.

**Comment by kmxillo** [comment]
I am still getting the same error as the initial one: 
`SSL Error {:exception=>#<OpenSSL::SSL::SSLError: Received fatal alert: unknown_ca>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:272:in `accept'"`

Using beats-input-plugin works as expected. 

logstash-input-tcp-4.1.0
